accounts/urls.py
from django.urls import re_path
from . import views 
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'


urlpatterns = [
    re_path(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    re_path(r'^login/$', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
]

quizapp/urls.py
from django.urls import re_path
from . import views

app_name = 'quizapp'

urlpatterns = [
    re_path(r'^list', views.Quiz.as_view(), name='list'),
    re_path(r'^detail/(?P<pk>\d+)',
            views.QuizDetailView.as_view(), name='detail'),
    re_path(r'choice/(?P<pk>\d+)', views.choice, name='choice'),
    re_path(r'results/', views.ResultsView.as_view(), name='results'),
    re_path(r'^$', views.list_page, name='list'),
    re_path(r'^hello/', views.create_list, name='hello'),
    re_path(r'^create/(?P<pk>\d+)', views.create_test_view, name='create'),
]

quizproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^index/$', views.IndexView.as_view(), name='index'),
    re_path(r'^test/$', views.TestPageView.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPageView.as_view(), name='thanks'),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^quizapp/', include('quizapp.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" />
    <title>Base</title>
</head>

<body class="bg-secondary">
    <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
        <a class="navbar-brand font-weight-bold" href="{% url 'index' %}">Home</a>
        <ul class="navbar-nav">
            <!-- {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'quizapp:list' %}" class="font-weight-bold nav-link">Give A Test</a></li>
            <li class="nav-item"><a href="{% url 'quizapp:hello' %}" class="font-weight-bold nav-link">Create Test</a></li>
            <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="font-weight-bold nav-link">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url 'accounts:login' %}" class="font-weight-bold nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="font-weight-bold nav-link">SignUp</a></li>
            {% endif %} -->
            <li class="nav-item"><a href="{% url 'quizapp:list' %}" class="font-weight-bold nav-link">Give A Test</a></li>
            <li class="nav-item"><a href="{% url 'quizapp:hello' %}" class="font-weight-bold nav-link">Create Test</a></li>
        </ul>
    </nav>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to Quiz Challange Page</h1>

{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}

<h1>You are now Logged In. Enjoy!!!!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}

<h1>Thanks For visiting. Come Back Soon.</h1>

{% endblock %}