quizapp/urls.py
from django.urls import re_path
from . import views

app_name = 'quizapp'

urlpatterns = [
    re_path(r'^list', views.Quiz.as_view(), name='list'),
    re_path(r'^detail/(?P<pk>\d+)',
            views.QuizDetailView.as_view(), name='detail'),
    re_path(r'choice/(?P<pk>\d+)', views.choice, name='choice'),
    re_path(r'results/', views.ResultsView.as_view(), name='results'),
    re_path(r'^$', views.list_page, name='list'),
    re_path(r'^hello/', views.create_list, name='hello'),
    re_path(r'^create/(?P<pk>\d+)', views.create_test_view, name='create'),
]

quizproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^index/$', views.IndexView.as_view(), name='index'),
    re_path(r'^test/$', views.TestPageView.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPageView.as_view(), name='thanks'),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^quizapp/', include('quizapp.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import redirect

User = get_user_model()

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=255)

    def __str__(self):
        return str(self.question_text)


class Answer(models.Model):
    answer_text = models.CharField(max_length=255)
    answer_image = models.ImageField(upload_to='profile/', null=True, blank=True)
    related_to = models.ForeignKey(
        Question, blank=True, null=True, on_delete=models.CASCADE)
    right_ans = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_text

    def update_ans(self):
        self.right_ans = True
        self.save()
    
    def undo_ans(self):
        self.right_ans = False
        self.save()

class Result(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField()

    def __str__(self):
        return str(self.user.score)

    def get_absolute_url(self):
        return redirect("quizapp:detail", pk=self.pk)


class User_specific_model(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_answer = models.ForeignKey(Answer, on_delete=models.CASCADE)


# if __name__ == '__main__':
#     n = int(input())
#     student_marks = {}
#     for _ in range(n):
#         name, *line = input().split()
#         scores = list(map(float, line))
#         student_marks[name] = scores
#     query_name = input()

quizapp/forms.py
from django import forms
from .models import Question, Answer


class CreateTestForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)


# class CreateTestFormAns(forms.ModelForm):
#     class Meta:
#         model = Answer
#         fields = ('answer_text',)
    

quizapp/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Question, Answer, Result
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404
# from .forms import CreateTestForm
# Create your views here.


def start_page(request):
    
    return render(request, "quizapp/startpage.html", {})


def list_page(request):
    quest = Question.objects.filter(pk=1)
    quest_pk = quest.values('pk')[0].get('pk')
    print(quest_pk)
    if request.POST:
        name  = request.POST.get('username')
        print(name)
        if name == '' or name == None:
            messages.error(request, "Please enter a username")
        else:
            messages.success(request, "Username is: %s"%name)
            return redirect('quizapp:detail', pk=quest_pk)
    context = {
        'pk': quest_pk,
        'question': quest,
        }
    return render(request, 'quizapp/startpage.html', context)
    # q = quest.values('question_text')
    

def create_list(request):
    quest = Question.objects.filter(pk=1)
    quest_pk = quest.values('pk')[0].get('pk')
    print(quest_pk)
    # q = quest.values('question_text')
    if request.POST:
        name  = request.POST.get('username')
        print(name)
        if name == '' or name == None:
            messages.error(request, "Please enter a username")
        else:
            messages.success(request, "Username is: %s"%name)
            return redirect('quizapp:create', pk=quest_pk)
    context = {
        'pk': quest_pk,
        'question': quest,
    }
    return render(request, 'quizapp/temp.html', context)


class Quiz(generic.ListView):
    model = Question
    template_name = 'quizapp/question_list.html'


class QuizDetailView(generic.DetailView):
    model = Question
    template_name = 'quizapp/question_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(QuizDetailView, self).get_context_data(*args, **kwargs)
        answer = Answer.objects.filter(related_to=self.kwargs.get('pk'))
        context['answer'] = answer
        return context

    # def get_queryset(self):
    #     try:
    #         radio = self.request.GET.get('selected')
    #         print(radio)
    #     except (TypeError, Answer.DoesNotExist):
    #         messages.warning('Select the items please')
    #     print(self.kwargs.get('pk'))
    #     answer = Answer.objects.filter(related_to=self.kwargs.get('pk'))
    #     print(answer)
    #     correct_answer = answer.filter(right_ans=True).values('answer_text')
    #     ans = correct_answer[0].get('answer_text')
    #     print(ans)
    #     if ans == radio:
    #         print('You Got It Correct')
    #         messages.success(self.request, 'You Got It Correct')
    #     else:
    #         print('Sorry You Got It Wrong')
    #         messages.warning(self.request, 'Sorry You Got It Wrong')


points = 0


def choice(request, pk):
    question = get_object_or_404(Question, pk=pk)
    global points
    if question == 1:
        points = 0

    try:
        # print(question.answer_set.get(pk=request.GET.get('choice')))
        # selected_choice = question.answer_set.get(pk=request.GET.get('choice'))
        selected_choice = request.GET.get('choice')
        selected_ans = Answer.objects.filter(pk=selected_choice).values('answer_text')[0].get('answer_text')
        # print(selected_ans1)
        # print(selected_choice)
        # print(selected_choice1)
        # selected_ans = request.GET.get('answer_text')
        # print(selected_ans)
        # print(request.GET.get('choice'))
    except (TypeError, Answer.DoesNotExist):
        messages.warning(request, 'Select the choice first')
    else:
        answer = Answer.objects.filter(related_to=pk)
        # print(answer)
        correct_answer = answer.filter(right_ans=True).values('answer_text')
        # print(correct_answer)
        ans = correct_answer[0].get('answer_text')
        print(ans)
        # print(ans)
        new_pk = int(pk)+1
        # print(selected_choice, ans)
        if ans == selected_ans:
            messages.success(request, "you got it correct")
            print('right')
            points = points + 1
            print(points)
        else:
            messages.warning(request, 'sorry you got it wrong')
            print('wrong')

    if new_pk <= 10:
        return redirect('quizapp:detail', pk=new_pk)
    else:
        p = Result(score=points)
        p.save()
        return redirect('quizapp:results')

class ResultsView(generic.ListView):
    model = Result
    template_name = 'quizapp/results.html'



def create_test_view(request, pk):
    quest_pk = pk
    # print(quest_pk)
    quest = Question.objects.filter(pk=quest_pk)
    quest_text = quest.values('question_text')[0].get('question_text')
    # print(quest_text)

    ans = Answer.objects.filter(related_to=quest_pk)
    # print(ans)
    context = {
        'quest': quest_text,
        'ans': ans,
    }
    if request.POST:
        correct_ans = request.POST.get('choose')
        # try_ans = request.POST.get('try')
        # print("This is what i want")
        # print(try_ans)
        # print(correct_ans)
        if correct_ans:
            # print(ans.get(right_ans=True).exists())
            # if ans.get(right_ans=True):
            #     prev_ans = ans.get(right_ans=True)
            # # print(prev_ans)
            # if prev_ans == None:
            #     new_pk = int(pk) + 1
            #     new_ans = ans.get(answer_text=correct_ans)
            #     new_ans.update_ans()
            # elif prev_ans != correct_ans:
            #     new_pk = int(pk) + 1
            #     new_ans = ans.get(answer_text=correct_ans)
            #     # print(new_ans)
            #     new_ans.update_ans()
            #     prev_ans.undo_ans()
            new_pk = int(pk) + 1
            new_ans = ans.get(answer_text=correct_ans)
            new_ans.update_ans()
            answer = Answer.objects.filter(answer_text=correct_ans)
            answer.right_ans = True
        if new_pk <= 10:
            return redirect("quizapp:create", pk=new_pk)
        else:
            return redirect("index")
    return render(request, 'quizapp/createtest.html', context=context)
    # form = CreateTestForm(request.POST or None)
    # context = {
    #     'form': form,
    # }
    # return render(request, 'quizapp/createtest.html', context=context)

quizapp/templates/quizapp/createtest.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h1 class="ml-5 mt-3 text-light">{{ quest }}</h1>
        <div class="row">
            {% for answer in ans %}
            <div class="card bg-dark col-lg-3 col-md-4 col-sm-12 mt-3 py-2 px-auto ml-5" style="width:250px;">
                <label>
                    <input type="radio" name='choose' style="width:0px; height:0px; opacity: 0px;" value="{{ answer.answer_text }}">
                    {% if answer.answer_image %}
                    <img src="{{ answer.answer_image.url }}" value="{{ answer.answer_text}}" name="choose" alt="img"
                        width="250px" height="180px" />
                    {% else %}
                </label>
                <p>{{ answer.answer_text }}</p>
                {% endif %}

            </div>
            {% endfor %}
        </div><br> <br>
        <center><button class="btn btn-success" type="submit">Submit</button></center>
    </form>
</div>
{% endblock %}

quizapp/templates/quizapp/question_detail.html
{% extends 'base.html' %}

{% block content %}

<!-- {% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %} -->


<div class="container">
  <form method="GET" action="{% url 'quizapp:choice' pk=question.id %}">
    {% csrf_token %}
    <h3>{{question.id}}/10</h3>
    <h2 class="ml-5 text-light">{{ question.question_text }}</h2>
    <div class="row">
      {% for ans in answer %}
      <div class="card bg-dark col-lg-3 col-md-4 col-sm-12 mt-3 py-2 px-auto ml-5" style="width:250px;">
        <label>
          <input type="radio" name='choice' style="width:0px; height:0px; opacity: 0px;" value="{{ ans.id }}">
          {% if ans.answer_image %}
          <img src="{{ ans.answer_image.url }}" value="{{ ans.answer_text }}" name="choice" alt="img" width="250px"
            height="180px" />
        </label>
        {% else %}
        <p>{{ ans.answer_text }}</p>
        {% endif %}
      </div>
      {% endfor %}
    </div>
    <br><br>
    <center>
      <button class="btn btn-success" type="submit">Submit</button>
    </center>
  </form>
</div>


{% endblock %}

quizapp/templates/quizapp/question_list.html
{% extends 'base.html' %} {% block content %}
<ul>
  {% for question in question_list %}
  <li>
    <a href="{% url 'quizapp:detail' pk=question.pk %}"> {{ question.id }} </a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

quizapp/templates/quizapp/results.html
{% extends 'base.html' %}

{% block content %}

<h1>Results
    {% for result in result_list %}
    {{ result.score }}
    {% endfor %}
</h1>

{% endblock %}

quizapp/templates/quizapp/startpage.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
{% if pk == 1 %}

<!-- <div class="px-auto mx-auto my-5"> -->
<div class="container">
    <!-- <div class="alert alert-primary" role="alert">
        A simple primary alert—check it out!
    </div> -->
    <h2 class="mx-auto mt-5 px-auto alert-primary heading1">Test Your Friendship</h2>
    <form method="POST">
        {% csrf_token %}
        {% for message in messages %}
        {% if message|safe == 'Please enter a username' %}
        <p class='error alert-danger'>{{ message|safe }}</p>
        {% endif %}
        {% endfor %}
        <div class="input-group mb-3">
            <input type="text" class='form-control' placeholder="Enter Your Name" name="username" aria-label="Recipient's username"
                aria-describedby="button-addon2"><br><br>
            <div class="input-group-append">
                <!-- <button class="btn btn-success" type="button">Start Quiz</button> -->
            </div>
        </div>

        <!-- <input type="text" placeholder="Enter Your Name" name="username" style="border:2px solid black;"><br><br> -->

        <button class='btn btn-success butt'> Start Quiz</button>
    </form>
</div>
<!-- </div> -->
{% endif %}
{% endblock %}

quizapp/templates/quizapp/temp.html
{% extends 'base.html' %}
{% block content %}

{% if pk == 1 %}
<!-- <a href="{% url 'quizapp:create' pk=pk %}"><button class='btn btn-success'> Start Quiz</button></a> -->
<div class="px-auto mx-auto my-5">
    <h2 class="mx-auto px-auto alert-primary heading1">Test Your Friendship</h2>
    <form method="POST">
        {% csrf_token %}
        {% for message in messages %}
        {% if message|safe == 'Please enter a username' %}
        <p class="error alert-danger">{{ message|safe }}</p>
        {% endif %}
        {% endfor %}
        <input type="text" class='form-control' placeholder="Enter Your Name" name="username" aria-label="Recipient's username"
            aria-describedby="button-addon2"><br><br>

        <!-- <input type="text" placeholder="Enter Your Name" name="username" style="border:2px solid black;"><br><br> -->

        <button class='btn btn-success butt'> Start Quiz</button>
    </form>
</div>
{% endif %}
{% endblock %}